### ISSUE TITLE
Error install plugin in Redmine 4.0.4

### ISSUE THREAD

**Issue by koren85** [two-pack/redmine_xlsx_format_issue_exporter#75] opened 2019-10-04 20:38 UTC
Hi! I'm get error when install plugin
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/concurrent-ruby-1.1.5/lib/concurrent/collection/map/mri_map_backend.rb:14:in `new'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/concurrent-ruby-1.1.5/lib/concurrent/collection/map/mri_map_backend.rb:14:in `initialize'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/concurrent-ruby-1.1.5/lib/concurrent/map.rb:125:in `initialize'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionview-5.2.3/lib/action_view/template/resolver.rb:42:in `initialize'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionview-5.2.3/lib/action_view/template/resolver.rb:56:in `new'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionview-5.2.3/lib/action_view/template/resolver.rb:56:in `initialize'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionview-5.2.3/lib/action_view/template/resolver.rb:137:in `new'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionview-5.2.3/lib/action_view/template/resolver.rb:137:in `initialize'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionview-5.2.3/lib/action_view/template/resolver.rb:213:in `initialize'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionview-5.2.3/lib/action_view/template/resolver.rb:348:in `initialize'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionview-5.2.3/lib/action_view/path_set.rb:93:in `new'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionview-5.2.3/lib/action_view/path_set.rb:93:in `block in typecast'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionview-5.2.3/lib/action_view/path_set.rb:90:in `map'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionview-5.2.3/lib/action_view/path_set.rb:90:in `typecast'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionview-5.2.3/lib/action_view/path_set.rb:42:in `unshift'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionview-5.2.3/lib/action_view/view_paths.rb:66:in `prepend_view_path'
/home/redmine/redmine/plugins/extra_queries/lib/extra_queries/late_patches/controllers/timelog_controller_patch.rb:24:in `report_with_eq'

**Comment by two-pack** [comment] 2019-10-21 12:50
I cannot reproduce your problem in my environment.
Can you write more details of your installation and environment?
See: [How to report issue](https://github.com/two-pack/redmine_xlsx_format_issue_exporter/wiki/How-to-report-issue)

**Comment by koren85** [comment] 2019-10-29 21:27
Hello!
There are no problems on a clean installation of Redmine. A compatibility error occurs with the http://rmplus.pro/redmine/plugins/extra_queries plugin. Can you help me fix the compatibility issue with the specified plugin?

**Comment by two-pack** [comment] 2019-10-29 21:45
I check Extra Queries plugin v2.3.9 and it uses alias_method_chain yet.
alias_method_chain will be deprecated on Rails 5, see rails/rails#19434.
So I think this problem should be fixed by extra_queries plugin.

See https://github.com/two-pack/redmine_xlsx_format_issue_exporter/issues/41#issuecomment-306531411

**Closed** 2019-10-29 21:45 UTC
Labels: wontfix
